#include<iostream.h>
#include<conio.h>
class xyz
{
	public:
	int a,b;
	void sum()
	{
		cout<<"Sum of values is "<<a+b;
	}

};
void main()
{
	int x;
	clrscr();
	xyz m;
	cout<<"Enter number : ";
	cin>>x;
	m.a=5;
	m.b=x;
	m.sum();
getch();
}

















































































































































































